# --- 统一定义输出目录 ---
# 将所有生成的可执行文件、库等都统一输出到 build/bin 目录下
set(OUTPUT_BINARY_DIR "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${OUTPUT_BINARY_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_BINARY_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUTPUT_BINARY_DIR})

# --- 宏观路径定义 ---
set(SOURCE_ROOT "${CMAKE_SOURCE_DIR}/src")